//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::albums::Entity as Albums;
pub use super::playlist_songs::Entity as PlaylistSongs;
pub use super::playlists::Entity as Playlists;
pub use super::settings::Entity as Settings;
pub use super::song::Entity as Song;
